version: '3'
volumes:
  mysql_data: {}
services:
  chalice-api:
    container_name: chalice_api
    build: .
    ports:
      - 8010:8000
    environment:
      DB_HOST: mysql-host
      DB_USER: root
      DB_PASSWORD: Mysql@123
      DB_NAME: chalice
      DB_PORT: 3306
      STAGE: dev
    networks:
      - mysql-network
    depends_on:
      - mysql-host
    links:
      - "mysql-host:mysql-host"
  mysql-host:
    container_name: mysql
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Mysql@123
      MYSQL_DB: chalice
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network
networks:
  mysql-network:
 


