version: '2'
volumes:
  mysql-data:
services:
  chalice-api:
    container_name: chalice_api
    build: .
    ports:
      - 8010:8000
    environment:
      - DB_HOST=mysql-host
      - DB_USER=root
      - DB_PASSWORD=Mysql@123
      - DB_NAME=chalice
      - DB_PORT=3306
      - STAGE=dev
    networks:
      - mysql-network
    depends_on:
      - mysql-host
    links:
      - "mysql-host:mysql-host"
  mysql-host:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@123
      - MYSQL_DATABASE=chalice
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Mysql@123
    ports:
      - 3306:3306
    networks:
      - mysql-network
networks:
  mysql-network:
 


